name: monitor_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.7
  flutter_svg: ^2.0.7
  camera: ^0.10.5+3
  path_provider: ^2.1.1
  path: ^1.8.3
  collection: ^1.17.1
  permission_handler: ^10.4.3
  marquee: ^2.2.3
  carousel_slider: ^4.2.1
  grouped_list: ^5.1.2
  http: ^1.1.0
  retrofit: ^4.0.1
  form_builder_validators: ^9.0.0
  flutter_form_builder: ^9.1.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  image: ^4.0.17
  intl: ^0.18.0
  json_annotation: ^4.8.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  file_picker: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/data/
